node {
    checkout scm

    stage('Build') {
        dir('Spring/MVCProjectJava'){
        withMaven(maven: 'maven') {
            if (isUnix()) {
                sh 'mvn -Dmaven.test.failure.ignore clean package'
            } else {
                bat 'mvn -Dmaven.test.failure.ignore clean package'
            }
        }
    }
    }
    stage('Deploy to Tomcat') {
        if (!isUnix()) {
        bat '''
        copy Spring\\MVCProjectJava\\target\\*.war "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\bbs2.war" /Y
        '''
    }
    }

    stage('Results') {
        junit 'JAVA/Spring/MVCProjectJava/target/surefire-reports/TEST-*.xml'
        archiveArtifacts artifacts: 'JAVA/Spring/MVCProjectJava/target/*.war', fingerprint: true
    }
}
