node {
    checkout scm

    stage('Build') {
        dir('Spring/MVCProjectJava'){
        withMaven(maven: 'maven') {
            if (isUnix()) {
                sh 'mvn -Dmaven.test.failure.ignore clean package'
            } else {
                bat 'mvn -Dmaven.test.failure.ignore clean package'
            }
        }
    }
    }
    stage('Deploy to Tomcat') {
        if (!isUnix()) {
        bat 'copy Spring\\MVCProjectJava\\target\\MVCProjectJava-0.0.1-SNAPSHOT.war "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\bbs2.war" /Y'
        bat '"C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\bin\\shutdown.bat"'
        bat 'timeout /t 5 /nobreak'
        bat '"C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\bin\\startup.bat"'
    }
    }

    stage('Results') {
        // junit 'JAVA/Spring/MVCProjectJava/target/surefire-reports/TEST-*.xml'
        archiveArtifacts artifacts: 'Spring/MVCProjectJava/target/*.war', fingerprint: true
    }
}
