properties([
    pipelineTriggers([
        githubPush()
    ])
])

node {
    checkout scm

    stage('Build') {
        dir('Spring/MVCProjectJava'){
        withMaven(maven: 'maven') {
            if (isUnix()) {
                sh 'mvn -Dmaven.test.failure.ignore clean package'
            } else {
                bat 'mvn -Dmaven.test.failure.ignore clean package'
            }
        }
    }
    }
    stage('Deploy to Tomcat') {
        if (!isUnix()) {
               bat '''
        copy Spring\\MVCProjectJava\\target\\MVCProjectJava-0.0.1-SNAPSHOT.war "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\bbs2.war" /Y
        '''
    }
    }

    stage('Copy Uploaded Images') {
    steps {
        bat '''
        copy C:\\JAVA\\Spring\\MVCProjectJava\\src\\main\\webapp\\resources\\upload\\*.* "C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\\BBS2\\resources\\upload\\" /Y
        '''
    }
}

    stage('Results') {
        // junit 'JAVA/Spring/MVCProjectJava/target/surefire-reports/TEST-*.xml'
        archiveArtifacts artifacts: 'Spring/MVCProjectJava/target/*.war', fingerprint: true
    }
}
